services:
    redis:
        image: redis:latest
        container_name: trt-redis
        ports: 
            - "6379:6379"
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

    postgresql:
        image: postgres:latest
        container_name: trt-postgres
        shm_size: 128mb
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}