# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: TRT ParserService CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
        - '**/*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
        - '**/*.md'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    env:           
      REDIS__PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS__HOST: ${{ secrets.REDIS_HOST }}
    
    services:
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
          
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: dotnet restore ./TrTracker/TrtParserService/TrtParserService.csproj
        
      - name: Build
        run: dotnet build ./TrTracker/TrtParserService/TrtParserService.csproj --no-restore

      #  TODO tests
      #- name: Test
      #  run: dotnet test ./TrTracker/Tests/TrtUploadServiceTests/TrtUploadServiceTests.csproj --no-build --verbosity normal
